name: Build the container image

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  image_name: ghcr.io/williamjacksn/pip-tools

jobs:
  build:
    name: Build the container image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
        matrix:
          python_version:
            - '3.9'
            - '3.10'
            - '3.11'
            - '3.12'
            - '3.13'

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the container image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PY_VERSION=${{ matrix.python_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.image_name }}:py${{ matrix.python_version }}

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          build-args: |
            PY_VERSION=${{ matrix.python_version }}
          cache-from: type=gha
          push: true
          tags: ${{ env.image_name }}:py${{ matrix.python_version }}
